# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/willian/CLionProjects/learn-opengl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/willian/CLionProjects/learn-opengl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/willian/CLionProjects/learn-opengl/CMakeFiles /home/willian/CLionProjects/learn-opengl/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/willian/CLionProjects/learn-opengl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ImGui

# Build rule for target.
ImGui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ImGui
.PHONY : ImGui

# fast build rule for target.
ImGui/fast:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/build
.PHONY : ImGui/fast

#=============================================================================
# Target rules for targets named learn_opengl

# Build rule for target.
learn_opengl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 learn_opengl
.PHONY : learn_opengl

# fast build rule for target.
learn_opengl/fast:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/build
.PHONY : learn_opengl/fast

home/willian/.include/imgui/imgui.o: home/willian/.include/imgui/imgui.cpp.o

.PHONY : home/willian/.include/imgui/imgui.o

# target to build an object file
home/willian/.include/imgui/imgui.cpp.o:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui.cpp.o
.PHONY : home/willian/.include/imgui/imgui.cpp.o

home/willian/.include/imgui/imgui.i: home/willian/.include/imgui/imgui.cpp.i

.PHONY : home/willian/.include/imgui/imgui.i

# target to preprocess a source file
home/willian/.include/imgui/imgui.cpp.i:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui.cpp.i
.PHONY : home/willian/.include/imgui/imgui.cpp.i

home/willian/.include/imgui/imgui.s: home/willian/.include/imgui/imgui.cpp.s

.PHONY : home/willian/.include/imgui/imgui.s

# target to generate assembly for a file
home/willian/.include/imgui/imgui.cpp.s:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui.cpp.s
.PHONY : home/willian/.include/imgui/imgui.cpp.s

home/willian/.include/imgui/imgui_demo.o: home/willian/.include/imgui/imgui_demo.cpp.o

.PHONY : home/willian/.include/imgui/imgui_demo.o

# target to build an object file
home/willian/.include/imgui/imgui_demo.cpp.o:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui_demo.cpp.o
.PHONY : home/willian/.include/imgui/imgui_demo.cpp.o

home/willian/.include/imgui/imgui_demo.i: home/willian/.include/imgui/imgui_demo.cpp.i

.PHONY : home/willian/.include/imgui/imgui_demo.i

# target to preprocess a source file
home/willian/.include/imgui/imgui_demo.cpp.i:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui_demo.cpp.i
.PHONY : home/willian/.include/imgui/imgui_demo.cpp.i

home/willian/.include/imgui/imgui_demo.s: home/willian/.include/imgui/imgui_demo.cpp.s

.PHONY : home/willian/.include/imgui/imgui_demo.s

# target to generate assembly for a file
home/willian/.include/imgui/imgui_demo.cpp.s:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui_demo.cpp.s
.PHONY : home/willian/.include/imgui/imgui_demo.cpp.s

home/willian/.include/imgui/imgui_draw.o: home/willian/.include/imgui/imgui_draw.cpp.o

.PHONY : home/willian/.include/imgui/imgui_draw.o

# target to build an object file
home/willian/.include/imgui/imgui_draw.cpp.o:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui_draw.cpp.o
.PHONY : home/willian/.include/imgui/imgui_draw.cpp.o

home/willian/.include/imgui/imgui_draw.i: home/willian/.include/imgui/imgui_draw.cpp.i

.PHONY : home/willian/.include/imgui/imgui_draw.i

# target to preprocess a source file
home/willian/.include/imgui/imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui_draw.cpp.i
.PHONY : home/willian/.include/imgui/imgui_draw.cpp.i

home/willian/.include/imgui/imgui_draw.s: home/willian/.include/imgui/imgui_draw.cpp.s

.PHONY : home/willian/.include/imgui/imgui_draw.s

# target to generate assembly for a file
home/willian/.include/imgui/imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui_draw.cpp.s
.PHONY : home/willian/.include/imgui/imgui_draw.cpp.s

home/willian/.include/imgui/imgui_impl_glfw.o: home/willian/.include/imgui/imgui_impl_glfw.cpp.o

.PHONY : home/willian/.include/imgui/imgui_impl_glfw.o

# target to build an object file
home/willian/.include/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui_impl_glfw.cpp.o
.PHONY : home/willian/.include/imgui/imgui_impl_glfw.cpp.o

home/willian/.include/imgui/imgui_impl_glfw.i: home/willian/.include/imgui/imgui_impl_glfw.cpp.i

.PHONY : home/willian/.include/imgui/imgui_impl_glfw.i

# target to preprocess a source file
home/willian/.include/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui_impl_glfw.cpp.i
.PHONY : home/willian/.include/imgui/imgui_impl_glfw.cpp.i

home/willian/.include/imgui/imgui_impl_glfw.s: home/willian/.include/imgui/imgui_impl_glfw.cpp.s

.PHONY : home/willian/.include/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
home/willian/.include/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui_impl_glfw.cpp.s
.PHONY : home/willian/.include/imgui/imgui_impl_glfw.cpp.s

home/willian/.include/imgui/imgui_impl_opengl3.o: home/willian/.include/imgui/imgui_impl_opengl3.cpp.o

.PHONY : home/willian/.include/imgui/imgui_impl_opengl3.o

# target to build an object file
home/willian/.include/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui_impl_opengl3.cpp.o
.PHONY : home/willian/.include/imgui/imgui_impl_opengl3.cpp.o

home/willian/.include/imgui/imgui_impl_opengl3.i: home/willian/.include/imgui/imgui_impl_opengl3.cpp.i

.PHONY : home/willian/.include/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
home/willian/.include/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui_impl_opengl3.cpp.i
.PHONY : home/willian/.include/imgui/imgui_impl_opengl3.cpp.i

home/willian/.include/imgui/imgui_impl_opengl3.s: home/willian/.include/imgui/imgui_impl_opengl3.cpp.s

.PHONY : home/willian/.include/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
home/willian/.include/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui_impl_opengl3.cpp.s
.PHONY : home/willian/.include/imgui/imgui_impl_opengl3.cpp.s

home/willian/.include/imgui/imgui_tables.o: home/willian/.include/imgui/imgui_tables.cpp.o

.PHONY : home/willian/.include/imgui/imgui_tables.o

# target to build an object file
home/willian/.include/imgui/imgui_tables.cpp.o:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui_tables.cpp.o
.PHONY : home/willian/.include/imgui/imgui_tables.cpp.o

home/willian/.include/imgui/imgui_tables.i: home/willian/.include/imgui/imgui_tables.cpp.i

.PHONY : home/willian/.include/imgui/imgui_tables.i

# target to preprocess a source file
home/willian/.include/imgui/imgui_tables.cpp.i:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui_tables.cpp.i
.PHONY : home/willian/.include/imgui/imgui_tables.cpp.i

home/willian/.include/imgui/imgui_tables.s: home/willian/.include/imgui/imgui_tables.cpp.s

.PHONY : home/willian/.include/imgui/imgui_tables.s

# target to generate assembly for a file
home/willian/.include/imgui/imgui_tables.cpp.s:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui_tables.cpp.s
.PHONY : home/willian/.include/imgui/imgui_tables.cpp.s

home/willian/.include/imgui/imgui_widgets.o: home/willian/.include/imgui/imgui_widgets.cpp.o

.PHONY : home/willian/.include/imgui/imgui_widgets.o

# target to build an object file
home/willian/.include/imgui/imgui_widgets.cpp.o:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui_widgets.cpp.o
.PHONY : home/willian/.include/imgui/imgui_widgets.cpp.o

home/willian/.include/imgui/imgui_widgets.i: home/willian/.include/imgui/imgui_widgets.cpp.i

.PHONY : home/willian/.include/imgui/imgui_widgets.i

# target to preprocess a source file
home/willian/.include/imgui/imgui_widgets.cpp.i:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui_widgets.cpp.i
.PHONY : home/willian/.include/imgui/imgui_widgets.cpp.i

home/willian/.include/imgui/imgui_widgets.s: home/willian/.include/imgui/imgui_widgets.cpp.s

.PHONY : home/willian/.include/imgui/imgui_widgets.s

# target to generate assembly for a file
home/willian/.include/imgui/imgui_widgets.cpp.s:
	$(MAKE) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/home/willian/.include/imgui/imgui_widgets.cpp.s
.PHONY : home/willian/.include/imgui/imgui_widgets.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/main.cpp.s
.PHONY : main.cpp.s

render/BasicObjLoader.o: render/BasicObjLoader.cpp.o

.PHONY : render/BasicObjLoader.o

# target to build an object file
render/BasicObjLoader.cpp.o:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/BasicObjLoader.cpp.o
.PHONY : render/BasicObjLoader.cpp.o

render/BasicObjLoader.i: render/BasicObjLoader.cpp.i

.PHONY : render/BasicObjLoader.i

# target to preprocess a source file
render/BasicObjLoader.cpp.i:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/BasicObjLoader.cpp.i
.PHONY : render/BasicObjLoader.cpp.i

render/BasicObjLoader.s: render/BasicObjLoader.cpp.s

.PHONY : render/BasicObjLoader.s

# target to generate assembly for a file
render/BasicObjLoader.cpp.s:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/BasicObjLoader.cpp.s
.PHONY : render/BasicObjLoader.cpp.s

render/Camera.o: render/Camera.cpp.o

.PHONY : render/Camera.o

# target to build an object file
render/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/Camera.cpp.o
.PHONY : render/Camera.cpp.o

render/Camera.i: render/Camera.cpp.i

.PHONY : render/Camera.i

# target to preprocess a source file
render/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/Camera.cpp.i
.PHONY : render/Camera.cpp.i

render/Camera.s: render/Camera.cpp.s

.PHONY : render/Camera.s

# target to generate assembly for a file
render/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/Camera.cpp.s
.PHONY : render/Camera.cpp.s

render/Context.o: render/Context.cpp.o

.PHONY : render/Context.o

# target to build an object file
render/Context.cpp.o:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/Context.cpp.o
.PHONY : render/Context.cpp.o

render/Context.i: render/Context.cpp.i

.PHONY : render/Context.i

# target to preprocess a source file
render/Context.cpp.i:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/Context.cpp.i
.PHONY : render/Context.cpp.i

render/Context.s: render/Context.cpp.s

.PHONY : render/Context.s

# target to generate assembly for a file
render/Context.cpp.s:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/Context.cpp.s
.PHONY : render/Context.cpp.s

render/Interface.o: render/Interface.cpp.o

.PHONY : render/Interface.o

# target to build an object file
render/Interface.cpp.o:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/Interface.cpp.o
.PHONY : render/Interface.cpp.o

render/Interface.i: render/Interface.cpp.i

.PHONY : render/Interface.i

# target to preprocess a source file
render/Interface.cpp.i:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/Interface.cpp.i
.PHONY : render/Interface.cpp.i

render/Interface.s: render/Interface.cpp.s

.PHONY : render/Interface.s

# target to generate assembly for a file
render/Interface.cpp.s:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/Interface.cpp.s
.PHONY : render/Interface.cpp.s

render/Mesh.o: render/Mesh.cpp.o

.PHONY : render/Mesh.o

# target to build an object file
render/Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/Mesh.cpp.o
.PHONY : render/Mesh.cpp.o

render/Mesh.i: render/Mesh.cpp.i

.PHONY : render/Mesh.i

# target to preprocess a source file
render/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/Mesh.cpp.i
.PHONY : render/Mesh.cpp.i

render/Mesh.s: render/Mesh.cpp.s

.PHONY : render/Mesh.s

# target to generate assembly for a file
render/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/Mesh.cpp.s
.PHONY : render/Mesh.cpp.s

render/Model.o: render/Model.cpp.o

.PHONY : render/Model.o

# target to build an object file
render/Model.cpp.o:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/Model.cpp.o
.PHONY : render/Model.cpp.o

render/Model.i: render/Model.cpp.i

.PHONY : render/Model.i

# target to preprocess a source file
render/Model.cpp.i:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/Model.cpp.i
.PHONY : render/Model.cpp.i

render/Model.s: render/Model.cpp.s

.PHONY : render/Model.s

# target to generate assembly for a file
render/Model.cpp.s:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/Model.cpp.s
.PHONY : render/Model.cpp.s

render/Shader.o: render/Shader.cpp.o

.PHONY : render/Shader.o

# target to build an object file
render/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/Shader.cpp.o
.PHONY : render/Shader.cpp.o

render/Shader.i: render/Shader.cpp.i

.PHONY : render/Shader.i

# target to preprocess a source file
render/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/Shader.cpp.i
.PHONY : render/Shader.cpp.i

render/Shader.s: render/Shader.cpp.s

.PHONY : render/Shader.s

# target to generate assembly for a file
render/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/learn_opengl.dir/build.make CMakeFiles/learn_opengl.dir/render/Shader.cpp.s
.PHONY : render/Shader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ImGui"
	@echo "... rebuild_cache"
	@echo "... learn_opengl"
	@echo "... home/willian/.include/imgui/imgui.o"
	@echo "... home/willian/.include/imgui/imgui.i"
	@echo "... home/willian/.include/imgui/imgui.s"
	@echo "... home/willian/.include/imgui/imgui_demo.o"
	@echo "... home/willian/.include/imgui/imgui_demo.i"
	@echo "... home/willian/.include/imgui/imgui_demo.s"
	@echo "... home/willian/.include/imgui/imgui_draw.o"
	@echo "... home/willian/.include/imgui/imgui_draw.i"
	@echo "... home/willian/.include/imgui/imgui_draw.s"
	@echo "... home/willian/.include/imgui/imgui_impl_glfw.o"
	@echo "... home/willian/.include/imgui/imgui_impl_glfw.i"
	@echo "... home/willian/.include/imgui/imgui_impl_glfw.s"
	@echo "... home/willian/.include/imgui/imgui_impl_opengl3.o"
	@echo "... home/willian/.include/imgui/imgui_impl_opengl3.i"
	@echo "... home/willian/.include/imgui/imgui_impl_opengl3.s"
	@echo "... home/willian/.include/imgui/imgui_tables.o"
	@echo "... home/willian/.include/imgui/imgui_tables.i"
	@echo "... home/willian/.include/imgui/imgui_tables.s"
	@echo "... home/willian/.include/imgui/imgui_widgets.o"
	@echo "... home/willian/.include/imgui/imgui_widgets.i"
	@echo "... home/willian/.include/imgui/imgui_widgets.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... render/BasicObjLoader.o"
	@echo "... render/BasicObjLoader.i"
	@echo "... render/BasicObjLoader.s"
	@echo "... render/Camera.o"
	@echo "... render/Camera.i"
	@echo "... render/Camera.s"
	@echo "... render/Context.o"
	@echo "... render/Context.i"
	@echo "... render/Context.s"
	@echo "... render/Interface.o"
	@echo "... render/Interface.i"
	@echo "... render/Interface.s"
	@echo "... render/Mesh.o"
	@echo "... render/Mesh.i"
	@echo "... render/Mesh.s"
	@echo "... render/Model.o"
	@echo "... render/Model.i"
	@echo "... render/Model.s"
	@echo "... render/Shader.o"
	@echo "... render/Shader.i"
	@echo "... render/Shader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

